#!/bin/bash

curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh

rvm reload
rvm install 2.3.0
rvm gemset create rails4
rvm gemset use rails4 --default

gem install rails --version "4.2.0" --no-ri --no-rdoc
